import { sql } from 'drizzle-orm';
import { index, integer, pgEnum, pgTable, text, timestamp, uniqueIndex, uuid, varchar } from 'drizzle-orm/pg-core';

export const userRole = pgEnum('user_role', ['PATIENT', 'CAREGIVER', 'BOOKING_STAFF', 'CLINIC_ADMIN', 'SYSTEM_ADMIN']);
export const slotState = pgEnum('slot_state', ['PUBLISHED', 'HELD', 'BOOKED', 'EXPIRED', 'BLOCKED', 'CANCEL_PENDING', 'RELEASE_PENDING', 'ERROR']);
export const holdStatus = pgEnum('hold_status', ['ACTIVE', 'COMMITTED', 'EXPIRED', 'RELEASED']);
export const bookingStatus = pgEnum('booking_status', ['CONFIRMED', 'CANCEL_PENDING', 'CANCELLED', 'RESCHEDULED', 'ERROR']);

const timestamps = { createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(), updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow() };

export const hospitals = pgTable('hospitals', { id: uuid('id').defaultRandom().primaryKey(), name: varchar('name', { length: 160 }).notNull(), status: varchar('status', { length: 32 }).notNull().default('ACTIVE'), configurationReference: varchar('configuration_reference', { length: 160 }), ...timestamps });
export const users = pgTable('users', { id: uuid('id').defaultRandom().primaryKey(), identityReference: varchar('identity_reference', { length: 160 }).notNull().unique(), displayName: varchar('display_name', { length: 160 }).notNull(), email: varchar('email', { length: 254 }), role: userRole('role').notNull(), status: varchar('status', { length: 32 }).notNull().default('ACTIVE'), ...timestamps });
export const patients = pgTable('patients', { id: uuid('id').defaultRandom().primaryKey(), userId: uuid('user_id').references(() => users.id), identityReference: varchar('identity_reference', { length: 160 }).notNull().unique(), status: varchar('status', { length: 32 }).notNull().default('ACTIVE'), ...timestamps });
export const clinics = pgTable('clinics', { id: uuid('id').defaultRandom().primaryKey(), hospitalId: uuid('hospital_id').notNull().references(() => hospitals.id), name: varchar('name', { length: 160 }).notNull(), status: varchar('status', { length: 32 }).notNull().default('ACTIVE'), configurationReference: varchar('configuration_reference', { length: 160 }), ...timestamps });
export const appointmentTypes = pgTable('appointment_types', { id: uuid('id').defaultRandom().primaryKey(), clinicId: uuid('clinic_id').notNull().references(() => clinics.id), name: varchar('name', { length: 160 }).notNull(), description: text('description'), durationMinutes: integer('duration_minutes').notNull(), eligibilityRuleReference: varchar('eligibility_rule_reference', { length: 160 }), status: varchar('status', { length: 32 }).notNull().default('ACTIVE'), ...timestamps });
export const clinicians = pgTable('clinicians', { id: uuid('id').defaultRandom().primaryKey(), name: varchar('name', { length: 160 }).notNull(), specialty: varchar('specialty', { length: 160 }), status: varchar('status', { length: 32 }).notNull().default('ACTIVE'), ...timestamps });
export const slots = pgTable('slots', { id: uuid('id').defaultRandom().primaryKey(), clinicId: uuid('clinic_id').notNull().references(() => clinics.id), appointmentTypeId: uuid('appointment_type_id').notNull().references(() => appointmentTypes.id), clinicianId: uuid('clinician_id').references(() => clinicians.id), startTime: timestamp('start_time', { withTimezone: true }).notNull(), endTime: timestamp('end_time', { withTimezone: true }).notNull(), state: slotState('state').notNull().default('PUBLISHED'), version: integer('version').notNull().default(1), ...timestamps }, (table) => [index('slots_availability_idx').on(table.clinicId, table.appointmentTypeId, table.startTime)]);
export const holds = pgTable('holds', { id: uuid('id').defaultRandom().primaryKey(), slotId: uuid('slot_id').notNull().references(() => slots.id), patientId: uuid('patient_id').notNull().references(() => patients.id), status: holdStatus('status').notNull().default('ACTIVE'), idempotencyKey: varchar('idempotency_key', { length: 160 }).notNull(), expiresAt: timestamp('expires_at', { withTimezone: true }).notNull(), version: integer('version').notNull().default(1), ...timestamps }, (table) => [uniqueIndex('holds_patient_idempotency_idx').on(table.patientId, table.idempotencyKey)]);
export const bookings = pgTable('bookings', { id: uuid('id').defaultRandom().primaryKey(), patientId: uuid('patient_id').notNull().references(() => patients.id), slotId: uuid('slot_id').notNull().references(() => slots.id), appointmentTypeId: uuid('appointment_type_id').notNull().references(() => appointmentTypes.id), clinicId: uuid('clinic_id').notNull().references(() => clinics.id), clinicianId: uuid('clinician_id').references(() => clinicians.id), status: bookingStatus('status').notNull().default('CONFIRMED'), idempotencyKey: varchar('idempotency_key', { length: 160 }).notNull(), cancelledAt: timestamp('cancelled_at', { withTimezone: true }), ...timestamps }, (table) => [uniqueIndex('bookings_patient_idempotency_idx').on(table.patientId, table.idempotencyKey), uniqueIndex('one_active_booking_per_slot_idx').on(table.slotId).where(sql`${table.status} in ('CONFIRMED', 'CANCEL_PENDING')`)]);
export const idempotencyCommands = pgTable('idempotency_commands', { id: uuid('id').defaultRandom().primaryKey(), patientId: uuid('patient_id').notNull().references(() => patients.id), operation: varchar('operation', { length: 32 }).notNull(), idempotencyKey: varchar('idempotency_key', { length: 160 }).notNull(), requestHash: varchar('request_hash', { length: 64 }).notNull(), status: varchar('status', { length: 32 }).notNull().default('IN_PROGRESS'), response: text('response'), correlationId: varchar('correlation_id', { length: 160 }).notNull(), ...timestamps }, (table) => [uniqueIndex('idempotency_commands_patient_operation_key_idx').on(table.patientId, table.operation, table.idempotencyKey)]);
export const auditEvents = pgTable('audit_events', { id: uuid('id').defaultRandom().primaryKey(), actorId: uuid('actor_id').references(() => users.id), action: varchar('action', { length: 64 }).notNull(), targetType: varchar('target_type', { length: 64 }).notNull(), targetId: uuid('target_id'), outcome: varchar('outcome', { length: 32 }).notNull(), correlationId: varchar('correlation_id', { length: 160 }).notNull(), occurredAt: timestamp('occurred_at', { withTimezone: true }).notNull().defaultNow() });
